declare var __VLS_13: {
    hitBars: {
        [x: string]: any;
        [x: number]: any;
        ganttBarConfig: {
            id: string;
            label?: string | undefined;
            html?: string | undefined;
            hasHandles?: boolean | undefined;
            immobile?: boolean | undefined;
            bundle?: string | undefined;
            pushOnOverlap?: boolean | undefined;
            pushOnConnect?: boolean | undefined;
            dragLimitLeft?: number | undefined;
            dragLimitRight?: number | undefined;
            class?: string | undefined;
            milestoneId?: string | undefined;
            progress?: number | undefined;
            progressResizable?: boolean | undefined;
            plannedStyle?: {
                width?: string | number | undefined;
                height?: string | number | undefined;
                minWidth?: string | number | undefined;
                maxWidth?: string | number | undefined;
                minHeight?: string | number | undefined;
                maxHeight?: string | number | undefined;
                position?: "static" | "relative" | "absolute" | "fixed" | "sticky" | undefined;
                top?: string | number | undefined;
                right?: string | number | undefined;
                bottom?: string | number | undefined;
                left?: string | number | undefined;
                zIndex?: number | undefined;
                display?: string | undefined;
                opacity?: number | undefined;
                visibility?: "visible" | "hidden" | "collapse" | undefined;
                overflow?: "visible" | "hidden" | "scroll" | "auto" | undefined;
                flex?: string | number | undefined;
                flexGrow?: number | undefined;
                flexShrink?: number | undefined;
                flexBasis?: string | number | undefined;
                flexDirection?: "row" | "row-reverse" | "column" | "column-reverse" | undefined;
                justifyContent?: string | undefined;
                alignItems?: string | undefined;
                margin?: string | number | undefined;
                marginTop?: string | number | undefined;
                marginRight?: string | number | undefined;
                marginBottom?: string | number | undefined;
                marginLeft?: string | number | undefined;
                padding?: string | number | undefined;
                paddingTop?: string | number | undefined;
                paddingRight?: string | number | undefined;
                paddingBottom?: string | number | undefined;
                paddingLeft?: string | number | undefined;
                color?: string | undefined;
                backgroundColor?: string | undefined;
                background?: string | undefined;
                border?: string | undefined;
                borderRadius?: string | number | undefined;
                borderWidth?: string | number | undefined;
                borderColor?: string | undefined;
                borderStyle?: string | undefined;
                fontSize?: string | number | undefined;
                fontWeight?: string | number | undefined;
                fontFamily?: string | undefined;
                lineHeight?: string | number | undefined;
                textAlign?: "left" | "right" | "center" | "justify" | undefined;
                textTransform?: "none" | "uppercase" | "lowercase" | "capitalize" | undefined;
                cursor?: string | undefined;
                pointerEvents?: "auto" | "none" | undefined;
                transition?: string | undefined;
                transform?: string | undefined;
                overflowX?: "visible" | "hidden" | "scroll" | "auto" | undefined;
                overflowY?: "visible" | "hidden" | "scroll" | "auto" | undefined;
            } | undefined;
            _previousLabel?: string | undefined;
            connections?: {
                label?: string | undefined;
                targetId: string;
                type?: import("../types").ConnectionType | undefined;
                color?: string | undefined;
                pattern?: import("../types").ConnectionPattern | undefined;
                animated?: boolean | undefined;
                animationSpeed?: import("../types").ConnectionSpeed | undefined;
                relation?: import("../types").ConnectionRelation | undefined;
                labelAlwaysVisible?: boolean | undefined;
            }[] | undefined;
        };
    }[];
    datetime: string;
};
type __VLS_Slots = {} & {
    'pointer-marker-tooltips'?: (props: typeof __VLS_13) => any;
};
declare const __VLS_base: import("vue").DefineComponent<{}, {}, {}, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").PublicProps, Readonly<{}> & Readonly<{}>, {}, {}, {}, {}, string, import("vue").ComponentProvideOptions, true, {}, any>;
declare const __VLS_export: __VLS_WithSlots<typeof __VLS_base, __VLS_Slots>;
declare const _default: typeof __VLS_export;
export default _default;
type __VLS_WithSlots<T, S> = T & {
    new (): {
        $slots: S;
    };
};
