export interface GanttCSSProperties {
    width?: string | number;
    height?: string | number;
    minWidth?: string | number;
    maxWidth?: string | number;
    minHeight?: string | number;
    maxHeight?: string | number;
    position?: "static" | "relative" | "absolute" | "fixed" | "sticky";
    top?: string | number;
    right?: string | number;
    bottom?: string | number;
    left?: string | number;
    zIndex?: number;
    display?: string;
    opacity?: number;
    visibility?: "visible" | "hidden" | "collapse";
    overflow?: "visible" | "hidden" | "scroll" | "auto";
    flex?: string | number;
    flexGrow?: number;
    flexShrink?: number;
    flexBasis?: string | number;
    flexDirection?: "row" | "row-reverse" | "column" | "column-reverse";
    justifyContent?: string;
    alignItems?: string;
    margin?: string | number;
    marginTop?: string | number;
    marginRight?: string | number;
    marginBottom?: string | number;
    marginLeft?: string | number;
    padding?: string | number;
    paddingTop?: string | number;
    paddingRight?: string | number;
    paddingBottom?: string | number;
    paddingLeft?: string | number;
    color?: string;
    backgroundColor?: string;
    background?: string;
    border?: string;
    borderRadius?: string | number;
    borderWidth?: string | number;
    borderColor?: string;
    borderStyle?: string;
    fontSize?: string | number;
    fontWeight?: string | number;
    fontFamily?: string;
    lineHeight?: string | number;
    textAlign?: "left" | "right" | "center" | "justify";
    textTransform?: "none" | "uppercase" | "lowercase" | "capitalize";
    cursor?: string;
    pointerEvents?: "auto" | "none";
    transition?: string;
    transform?: string;
    overflowX?: "visible" | "hidden" | "scroll" | "auto";
    overflowY?: "visible" | "hidden" | "scroll" | "auto";
}
export type GanttColor = string;
